# Generated by Django 2.1.12 on 2019-10-19 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple',
            name='City',
        ),
        migrations.RemoveField(
            model_name='multiple',
            name='slug',
        ),
    ]
