# Generated by Django 2.1.12 on 2019-10-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order',
            name='Dropoffto',
            field=models.CharField(choices=[('neighbour', 'neighbour'), ('Security Guard', 'Security Guard'), ('mailbox', 'mailbox'), ('Any of the above', 'Any of the above')], max_length=255),
        ),
    ]
