# Generated by Django 2.1.13 on 2019-10-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_post', '0002_auto_20191019_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_order',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
